## runAnalyzer.py
## Author: James Wetzel
## james-wetzel@uiowa.edu
##
## This script is to be run in the directory of root files generated by the qCal GEANT4 simulation
## http://github.com/jwwetzel/qcal
##
## Usage:
## $> cd Dir_With_qCalAnalyzer.root_Files
## $> python runAnalyzer.py
##
##

##import ROOT library as r, access root objects with r.object

# Solutions to having many root files: 
# 1) merge all same energy root files histograms to create a single histogram 

import ROOT as r

from string import Template
from array import array
import matplotlib.pyplot as plt
import numpy as np
import os
import csv
import sys

particle = sys.argv[1]
units = sys.argv[2]

## Function that provides progress by displaying how many files have been analyzed
## Example, consider 3 input files:  file1.root, file2.root, file3.root
## Progress would be:
## $> - - -  (Analyzing first file)
## $> # - -  (2nd file)
## $> # # -  (3rd file)
## $> # # #  (finished)
def printProgress(currentFile, totalFiles):
   print ""
   print "Progress: ",
   progress = totalFiles - currentFile
   for i in range(0,currentFile):
      print "#",
   for i in range(0,progress):
      print "-",
   print ""
   print ""

objCount = 2
################################
# Object List: 
# 0 Photon counts
# 1 times
# 2
################################

## Dictionary definitions
files = {}                                         # For storing the filenames found in the directories
hists = {}                                         # For storing the created histograms from analyzing each file
#objectNameDict = {0 : 'totalPhotons', 1: 'HitTimes'}    # MUST BE BRANCH NAMES IN ROOT FILES

energies = array( 'd' ) # Arrays for the TGraph scatter plot of hits vs energy
fitMeans = {}
fitStds = {}
#fitResults_times, hitTimes =  array( 'd' ), array( 'd' ) 

outF = r.TFile("Analyzed.root","RECREATE")         # Output root file for storing the analyzed products.

# GET THE FILES
fileIterator = 0                                               # for counting through the files
for file in os.listdir("."):                                  # Loop over the files in the current directory
   if file.endswith("10000.root") and file.split("-")[1].split("_")[0] == units:                                # Look only for .root files
      if file.startswith("Analyzed"):                          # Ignore the output ROOT file so you can recreate it each time.
         continue
      energies.append(int(file.split("_")[1].split("-")[0]))   # This takes the energy from the root file name:  muons_120-GeV_1k.root -> 120
      files[energies[fileIterator]] = file
      fileIterator+=1


## GET THE HISTOGRAMS
fileIterator = 0   
for E, file in files.iteritems(): 

   #printProgress(file,len(files))                                                                        # Print progress
   processLine = '.x analyzeCal.C+("{0}")'.format(file) 
   #processLine = '.x ~/Dropbox/Research/GEANT/qCal/Analysis/analyzeCal.C+("{0}")'.format(files[file])    # format ROOT command for running analyzeCal.C
   # Run analyzeCal.C in ROOT runtime environment
   r.gROOT.ProcessLine(processLine)  
  
   hists[E] =     r.gROOT.FindObject("PhotonCountHist")                                       # After running, analyzeCal.C returns a TH1F
   hists[E].SetName("PhotonCountHist" + str(energies[fileIterator]))                   # Change the name of the histogram to current energy, prefixed by object name
   hists[E].SetDirectory(0)                                                                           # Decouple the histogram object from the ROOT environment
   outF.cd()                                                                                             # Change Directory (cd) to Analyzed.root file to save histogram
   hists[E].Write()                                                                                   # Save the histogram to the Analyzed.root file
  
   fileIterator+=1

## MAKE A CANVAS
canvas = r.TCanvas("canv1","Hits per GeV",800,800)    # Create a blank canvas to draw the histograms onto
canvas.cd()       
#canvas.SetLogy()                                # Set this canvas to the current active canvas
#canvas.GetXaxis().SetRangeUser(0, 30000)

                                     # Make the y-axis log scale

## FIT THE HISTOGRAMS && AND DRAW ON CANVAS
actualEnergies = np.sort(np.array([n for n in energies]))

for E, file in files.iteritems(): 
   fit = r.TF1("gaus","gaus(0)")                         # Define the fit object to be a Gaussian
   fit.SetParameter(1,hists[E].GetMean())             # Initialize the fit object to the mean of the histogram...
   fit.SetParameter(2,hists[E].GetStdDev())           # ...and the std. deviation as a starting point for the fit
   #hists[E].Scale(1/hists[E].Integral(),"Width")   # Normalize the histograms to 1
   #hists[E].Rebin(50)
   #hists[E].SetMarkerStyle(kFullCircle)
   hists[E].Draw("Same PLC PMC")                              # Draw the histogram, the "Same" argument keeps previous content on the Canvas
  
   hists[E].Fit(fit)                                  # Fit the curve
   fit.Draw("Same")                                      # Draw the fit onto the histogram
   fitMeans[E] =hists[E].GetMean()       # Store the mean to the fitResults_energy array for plotting hits vs. energy
   fitStds[E] = hists[E].GetStdDev()   

means = np.zeros(len(actualEnergies))
stds = np.zeros(len(actualEnergies))
for i in range(0, len(actualEnergies)):
   E = actualEnergies[i]
   means[i] = fitMeans[E]
   stds[i] = fitStds[E]
   #print("ENERGY: ", E, "MEAN: ", fitMeans[E], "STD: ", fitStds[E])


row0 = ['0']
row1 = ['1']
row2 = ['2']
row3 = ['3']

# the actual energies need MeV, GeV
# no the python script needs a command line argument that is MeV or GeV
# but the files with MeV and GeV args are the same 
# either need two different files with different data
# or need one file with 28*2 = 56 rows
# the catch is this folder contains only GeV files with MeV names 
for i in range(0, len(actualEnergies)):
   row1.append(str(actualEnergies[i]))
   row2.append(str(means[i]))
   row3.append(str(stds[i]))

rows = [row0, row1, row2, row3]
with open(particle + "_" + units + '.csv', 'w') as writeFile:

   writer = csv.writer(writeFile)
   writer.writerows(rows)
writeFile.close()
