// analyzeCal.C
// Author: James Wetzel
// james-wetzel@uiowa.edu
//
// This script loops over trees generated by the qCal GEANT4 Simulation
// http://github.com/jwwetzel/qcal
//
// Usage:
// root [0]> .x analyzeCal.C+("muons_120-GeV_1k.root")
//
// The output is a TH1F, and the input is a root file.

#include <TH2.h>
#include <TStyle.h>
#include <TCanvas.h>
#include <TH1F.h>
#include <TFile.h>
#include "TTree.h"
#include "TTreeReader.h"
#include "TTreeReaderValue.h"
#include "TTreeReaderArray.h"

#include <iostream>
#include <string>
#include <vector> 

using namespace std;  // So you don't have to put std:: in front of cout and other things

TH1D analyzeCal(char const *fileName)
{
   TFile *f = new TFile(fileName,"READ");                                        // Open the input file READ only to avoid messing it up
   cout << "Grabbing histograms: " << fileName << endl;

   TH1D* hitsPerEvent = new TH1D();
   //int eventCounter = 0;                                                         // For keeping track of progress and debugging (add to loop to limit runs)
   f->GetObject("PhotonCountHist", hitsPerEvent);
   return *hitsPerEvent;           // Return the histogram.
}

